# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImagesService/images_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ImagesService/images_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\"ImagesService/images_service.proto\"`\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\r\n\x05\x61\x64min\x18\x05 \x01(\x08\"S\n\x05Image\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07updated\x18\x03 \x01(\x03\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x0f\n\x07\x61\x63tions\x18\x05 \x03(\t\"0\n\x06Images\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x14\n\x04list\x18\x02 \x03(\x0b\x32\x06.Image\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"E\n\x11ResponseWithImage\x12\x19\n\x06status\x18\x01 \x01(\x0b\x32\t.Response\x12\x15\n\x05image\x18\x02 \x01(\x0b\x32\x06.Image\"L\n\x16ResponseWithImagesList\x12\x19\n\x06status\x18\x01 \x01(\x0b\x32\t.Response\x12\x17\n\x06images\x18\x02 \x03(\x0b\x32\x07.Images\"B\n\x10ResponseWithUser\x12\x19\n\x06status\x18\x01 \x01(\x0b\x32\t.Response\x12\x13\n\x04user\x18\x02 \x01(\x0b\x32\x05.User2z\n\tImagesAPI\x12(\n\x04List\x12\x05.User\x1a\x17.ResponseWithImagesList\"\x00\x12$\n\x04\x46ind\x12\x06.Image\x1a\x12.ResponseWithImage\"\x00\x12\x1d\n\x06\x44\x65lete\x12\x06.Image\x1a\t.Response\"\x00\x32\x30\n\x08UsersAPI\x12$\n\x06Verify\x12\x05.User\x1a\x11.ResponseWithUser\"\x00\x62\x06proto3'
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='User.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='User.first_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='User.last_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='admin', full_name='User.admin', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=134,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Image.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Image.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated', full_name='Image.updated', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='Image.tags', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions', full_name='Image.actions', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=219,
)


_IMAGES = _descriptor.Descriptor(
  name='Images',
  full_name='Images',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='Images.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list', full_name='Images.list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=269,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Response.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=312,
)


_RESPONSEWITHIMAGE = _descriptor.Descriptor(
  name='ResponseWithImage',
  full_name='ResponseWithImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ResponseWithImage.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='ResponseWithImage.image', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=383,
)


_RESPONSEWITHIMAGESLIST = _descriptor.Descriptor(
  name='ResponseWithImagesList',
  full_name='ResponseWithImagesList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ResponseWithImagesList.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='ResponseWithImagesList.images', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=461,
)


_RESPONSEWITHUSER = _descriptor.Descriptor(
  name='ResponseWithUser',
  full_name='ResponseWithUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ResponseWithUser.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='ResponseWithUser.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=529,
)

_IMAGES.fields_by_name['list'].message_type = _IMAGE
_RESPONSEWITHIMAGE.fields_by_name['status'].message_type = _RESPONSE
_RESPONSEWITHIMAGE.fields_by_name['image'].message_type = _IMAGE
_RESPONSEWITHIMAGESLIST.fields_by_name['status'].message_type = _RESPONSE
_RESPONSEWITHIMAGESLIST.fields_by_name['images'].message_type = _IMAGES
_RESPONSEWITHUSER.fields_by_name['status'].message_type = _RESPONSE
_RESPONSEWITHUSER.fields_by_name['user'].message_type = _USER
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Images'] = _IMAGES
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['ResponseWithImage'] = _RESPONSEWITHIMAGE
DESCRIPTOR.message_types_by_name['ResponseWithImagesList'] = _RESPONSEWITHIMAGESLIST
DESCRIPTOR.message_types_by_name['ResponseWithUser'] = _RESPONSEWITHUSER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'ImagesService.images_service_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'ImagesService.images_service_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  })
_sym_db.RegisterMessage(Image)

Images = _reflection.GeneratedProtocolMessageType('Images', (_message.Message,), {
  'DESCRIPTOR' : _IMAGES,
  '__module__' : 'ImagesService.images_service_pb2'
  # @@protoc_insertion_point(class_scope:Images)
  })
_sym_db.RegisterMessage(Images)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'ImagesService.images_service_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

ResponseWithImage = _reflection.GeneratedProtocolMessageType('ResponseWithImage', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEWITHIMAGE,
  '__module__' : 'ImagesService.images_service_pb2'
  # @@protoc_insertion_point(class_scope:ResponseWithImage)
  })
_sym_db.RegisterMessage(ResponseWithImage)

ResponseWithImagesList = _reflection.GeneratedProtocolMessageType('ResponseWithImagesList', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEWITHIMAGESLIST,
  '__module__' : 'ImagesService.images_service_pb2'
  # @@protoc_insertion_point(class_scope:ResponseWithImagesList)
  })
_sym_db.RegisterMessage(ResponseWithImagesList)

ResponseWithUser = _reflection.GeneratedProtocolMessageType('ResponseWithUser', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEWITHUSER,
  '__module__' : 'ImagesService.images_service_pb2'
  # @@protoc_insertion_point(class_scope:ResponseWithUser)
  })
_sym_db.RegisterMessage(ResponseWithUser)



_IMAGESAPI = _descriptor.ServiceDescriptor(
  name='ImagesAPI',
  full_name='ImagesAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=531,
  serialized_end=653,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='ImagesAPI.List',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSEWITHIMAGESLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Find',
    full_name='ImagesAPI.Find',
    index=1,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_RESPONSEWITHIMAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='ImagesAPI.Delete',
    index=2,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESAPI)

DESCRIPTOR.services_by_name['ImagesAPI'] = _IMAGESAPI


_USERSAPI = _descriptor.ServiceDescriptor(
  name='UsersAPI',
  full_name='UsersAPI',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=655,
  serialized_end=703,
  methods=[
  _descriptor.MethodDescriptor(
    name='Verify',
    full_name='UsersAPI.Verify',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_RESPONSEWITHUSER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSAPI)

DESCRIPTOR.services_by_name['UsersAPI'] = _USERSAPI

# @@protoc_insertion_point(module_scope)
